### ISSUE TITLE
Unable to start npm run dev

### ISSUE THREAD

**Issue by gjorgic** [hoppscotch/hoppscotch#1818]
**Describe the bug**
Hi, I try run this project, but I have problem with runing `npm run dev`

Branch: `main` (`c3e881ed77c3829894326e03becae67a6307356d`)
node version: `v12.19.0`
npm version: `6.14.8`

Error
```

> hoppscotch@2.0.0 dev /projects/hoppscotch
> nuxt

ℹ windicss@3.1.6 running with config: windi.config.js                                                                                                                                                                 nuxt:windicss 09:06:59

 FATAL  Package subpath './dist/vue-composition-api.esm.js' is not defined by "exports" in /projects/hoppscotch/node_modules/@vue/composition-api/package.json                                                   09:06:59

  at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
  at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
  at resolveExports (internal/modules/cjs/loader.js:444:36)
  at Function.Module._findPath (internal/modules/cjs/loader.js:484:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
  at Function.resolve (internal/modules/cjs/helpers.js:80:19)
  at Function.p [as resolve] (node_modules/jiti/dist/jiti.js:1:52953)
  at Resolver.resolveModule (node_modules/@nuxt/core/dist/core.js:263:28)
  at ModuleContainer.compositionApiModule2 (node_modules/@nuxtjs/composition-api/dist/module/index.js:152:22)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)


   ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                               │
   │   ✖ Nuxt Fatal Error                                                                                                          │
   │                                                                                                                               │
   │   Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/vue-composition-api.esm.js' is not defined by "exports" in   │
   │   /projects/hoppscotch/node_modules/@vue/composition-api/package.json                                                         │
   │                                                                                                                               │
   ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoppscotch@2.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoppscotch@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Any idea? Thx

**Comment by liyasthomas** [comment]
Did you install the dependencies using `npm i`?

Follow the complete [local dev setup steps](https://github.com/hoppscotch/hoppscotch#local-development-environment).

**Comment by gjorgic** [comment]
Upgrading NodeJS and npm to latest version fix issue; Thanks @liyasthomas
