### ISSUE TITLE
[bug]: I clone the code to my computer, but the process 'pnpm install' failed.

### ISSUE THREAD

**Issue by fritz1149** [hoppscotch/hoppscotch#2910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I enter the directory of hoppscotch, having installed pnpm, and run 'pnpm install'.
Things seem go well at first, but then it failed, and the output is :

packages/hoppscotch-common postinstall$ pnpm run gql-codegen
│ > @hoppscotch/common@3.0.1 gql-codegen E:\Projects\hoppscotch\packages\hoppscotch-common
│ > graphql-codegen --require dotenv/config --config gql-codegen.yml dotenv_config_path="../../.env"
│ [STARTED] Parse Configuration
│ [SUCCESS] Parse Configuration
│ [STARTED] Generate outputs
│ [STARTED] Generate src/helpers/backend/graphql.ts
│ [STARTED] Load GraphQL schemas
│ [FAILED] Failed to load schema
│ [STARTED] Generate src/helpers/backend/backend-schema.json
│ [STARTED] Load GraphQL schemas
│ [FAILED] Failed to load schema
│ Failed to load schema for "src/helpers/backend/backend-schema.json"
│         Failed to load schema from undefined:
│
│       Unable to find any GraphQL type definitions for the following pointers:
│
│           - undefined
│
│         Error:
│       Unable to find any GraphQL type definitions for the following pointers:
│
│           - undefined
│
│     at prepareResult (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-tools+load@7.7.0_graphql@15.8.0\node_module
│     at loadTypedefs (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-tools+load@7.7.0_graphql@15.8.0\node_modules
│     at processTicksAndRejections (internal/process/task_queues.js:93:5)
│     at async loadSchema (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-tools+load@7.7.0_graphql@15.8.0\node_mod
│     at async loadSchema (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddo
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddonyyu\node_mo
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddonyyu\node_mo
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddonyyu\node_mo
│     at async Task.run (E:\Projects\hoppscotch\node_modules\.pnpm\listr2@4.0.5\node_modules\listr2\dist\index.cjs:979
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\p-map@4.0.0\node_modules\p-map\index.js:57:22
│         GraphQL Code Generator supports:
│           - ES Modules and CommonJS exports (export as default or named export "schema")
│           - Introspection JSON File
│           - URL of GraphQL endpoint
│           - Multiple files with type definitions (glob expression)
│           - String in config file
│         Try to use one of above options and run codegen again.
│
│ Failed to load schema for "src/helpers/backend/backend-schema.json"
│         Failed to load schema from undefined:
│
│       Unable to find any GraphQL type definitions for the following pointers:
│
│           - undefined
│
│         Error:
│       Unable to find any GraphQL type definitions for the following pointers:
│
│           - undefined
│
│     at prepareResult (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-tools+load@7.7.0_graphql@15.8.0\node_module
│     at loadTypedefs (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-tools+load@7.7.0_graphql@15.8.0\node_modules
│     at processTicksAndRejections (internal/process/task_queues.js:93:5)
│     at async loadSchema (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-tools+load@7.7.0_graphql@15.8.0\node_mod
│     at async loadSchema (E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddo
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddonyyu\node_mo
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddonyyu\node_mo
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\@graphql-codegen+cli@2.8.0_h5eoywvcjsa4emif44kddonyyu\node_mo
│     at async Task.run (E:\Projects\hoppscotch\node_modules\.pnpm\listr2@4.0.5\node_modules\listr2\dist\index.cjs:979
│     at async E:\Projects\hoppscotch\node_modules\.pnpm\p-map@4.0.0\node_modules\p-map\index.js:57:22
│         GraphQL Code Generator supports:
│           - ES Modules and CommonJS exports (export as default or named export "schema")
│           - Introspection JSON File
│           - URL of GraphQL endpoint
│           - Multiple files with type definitions (glob expression)
│           - String in config file
│         Try to use one of above options and run codegen again.
│
│ [SUCCESS] Generate outputs
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 4s at E:\Projects\hoppscotch\packages\hoppscotch-common
 ELIFECYCLE  Command failed with exit code 1.

### Steps to reproduce

1. Go to directory of hoppscotch 
2. pnpm install

### Environment

Production

### Version

Local

**Comment by aitchnyu** [comment]
You are likely to be missing `.env` file. Please run `$ cp .env.example .env`.

**Comment by ingxhe** [comment]
> You are likely to be missing `.env` file. Please run `$ cp .env.example .env` and then run `pnpm install` again.

Fack you
![image](https://github.com/hoppscotch/hoppscotch/assets/30750321/bfd44c7b-5e38-4194-a181-bc0d1f19b776)

**Comment by ingxhe** [comment]
> You are likely to be missing `.env` file. Please run `$ cp .env.example .env` and then run `pnpm install` again.

Your mother is dead！！！！！！！！
