### ISSUE TITLE
GraphQL Document Validation failed with 2 errors while Install dependencies by running `pnpm install`

### ISSUE THREAD

**Issue by fti-sfuke** [hoppscotch/hoppscotch#3034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
**Local development environment:** 
GraphQL Document Validation failed with 2 errors while Install dependencies by running pnpm install
    
**Environment details :**

OS Detail : 
```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# 

```
**Node Version and npm version :** 

```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# node -v
v16.14.2
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# npm -v
8.5.0

```

### Steps to reproduce

Local development environment

**1. Checkout `v3.0.1`**

```
 root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# git branch
* (HEAD detached at v3.0.1)
  main
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch#

```

**2. Install pnpm using npm by running `npm install -g pnpm`.**
```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# npm install -g pnpm

changed 1 package, and audited 2 packages in 596ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# 

```

**3. Install dependencies by running `pnpm install` within the directory** 
```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# pnpm install
Scope: all 6 workspace projects
Downloading registry.npmjs.org/typescript/4.7.4: 11.7 MB/11.7 MB, done
packages/hoppscotch-app                  |  WARN  deprecated subscriptions-transport-ws@0.11.0
packages/hoppscotch-cli                  |  WARN  deprecated @types/axios@0.14.0
packages/hoppscotch-cli                  |  WARN  deprecated @types/commander@2.12.2
packages/hoppscotch-cli                  |  WARN  deprecated @types/chalk@2.2.0
Downloading registry.npmjs.org/firebase/9.8.4: 6.48 MB/6.48 MB, done
packages/hoppscotch-app                  |  WARN  deprecated har-validator@5.1.5
packages/hoppscotch-app                  |  WARN  deprecated querystring@0.2.0
packages/hoppscotch-app                  |  WARN  deprecated rollup-plugin-inject@3.0.2
packages/hoppscotch-app                  |  WARN  deprecated xmldom@0.1.31
Downloading registry.npmjs.org/@swc/core-linux-x64-musl/1.2.213: 29.8 MB/29.8 MB, done
Downloading registry.npmjs.org/@swc/core-linux-x64-gnu/1.2.213: 29.9 MB/29.9 MB, done
packages/hoppscotch-app                  |  WARN  deprecated mkdirp-promise@1.1.0
packages/hoppscotch-app                  |  WARN  deprecated rollup-plugin-terser@7.0.2
Packages: +1489
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1533, reused 0, downloaded 1482, added 1489, done
node_modules/.pnpm/core-js@3.6.5/node_modules/core-js: Running postinstall script, done in 52ms
node_modules/.pnpm/vue-demi@0.13.1_vue@3.2.37/node_modules/vue-demi: Running postinstall script, done in 79ms
node_modules/.pnpm/protobufjs@6.11.3/node_modules/protobufjs: Running postinstall script, done in 62ms
node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild: Running postinstall script, done in 51ms
node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild: Running postinstall script, done in 75ms
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run:
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│ 
│ src/index.js → dist/index.cjs, ./dist...
│ created dist/index.cjs, ./dist in 1.3s
└─ Done in 1.8s
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code /root/hoppscotch/packages/hoppscotch-data
│ > vite build
│ vite v3.1.0 building for production...
│ transforming...
│ ✓ 287 modules transformed.
│ rendering chunks...
│ dist/hoppscotch-data.js   46.28 KiB / gzip: 13.39 KiB
│ dist/hoppscotch-data.cjs   34.28 KiB / gzip: 12.04 KiB
│ > @hoppscotch/data@0.4.4 build:decl /root/hoppscotch/packages/hoppscotch-data
│ > tsc --project tsconfig.decl.json
└─ Done in 3.1s
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 66ms
packages/hoppscotch-js-sandbox postinstall$ pnpm run build
[9 lines collapsed]
│ CJS Build start
│ CJS ⚡️ Build success in 13ms
│ ESM ⚡️ Build success in 70ms
│ ESM lib/index.mjs     18.97 KB
│ ESM lib/index.mjs.map 38.94 KB
│ CJS lib/index.js     20.05 KB
│ CJS lib/index.js.map 38.94 KB
│ DTS Build start
│ DTS ⚡️ Build success in 1454ms
│ DTS lib/index.d.ts 2.65 KB
└─ Done in 2.5s
packages/hoppscotch-app postinstall$ pnpm run gql-codegen
│ > hoppscotch-app@3.0.1 gql-codegen /root/hoppscotch/packages/hoppscotch-app
│ > graphql-codegen --config gql-codegen.yml
│ [STARTED] Parse Configuration
│ [SUCCESS] Parse Configuration
│ [STARTED] Generate outputs
│ [STARTED] Generate src/helpers/backend/graphql.ts
│ [STARTED] Load GraphQL schemas
│ (node:15830) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
│ (Use `node --trace-warnings ...` to show where the warning was created)
│ [SUCCESS] Load GraphQL schemas
│ [STARTED] Load GraphQL documents
│ [SUCCESS] Load GraphQL documents
│ [STARTED] Generate
│ [FAILED] GraphQL Document Validation failed with 2 errors;
│ [FAILED]   Error 0: GraphQLDocumentError: Variable "$cursor" of type "String" used in position expecting type "ID".
│ [FAILED]     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildren.graphql:1:49
│ [FAILED]     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildren.graphql:3:22
│ [FAILED] 
│ [FAILED] Error 1: GraphQLDocumentError: Variable "$cursor" of type "String" used in position expecting type "ID".
│ [FAILED]     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildrenIDs.graphql:1:52
│ [FAILED]     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildrenIDs.graphql:3:22
│ [STARTED] Generate src/helpers/backend/backend-schema.json
│ [STARTED] Load GraphQL schemas
│ [SUCCESS] Load GraphQL schemas
│ [STARTED] Load GraphQL documents
│ [SUCCESS] Load GraphQL documents
│ [STARTED] Generate
│ [SUCCESS] Generate
│ [SUCCESS] Generate src/helpers/backend/backend-schema.json
│ [SUCCESS] Generate outputs
│ GraphQL Document Validation failed with 2 errors;
│   Error 0: GraphQLDocumentError: Variable "$cursor" of type "String" used in position expecting type "ID".
│     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildren.graphql:1:49
│     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildren.graphql:3:22
│ Error 1: GraphQLDocumentError: Variable "$cursor" of type "String" used in position expecting type "ID".
│     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildrenIDs.graphql:1:52
│     at /root/hoppscotch/packages/hoppscotch-app/src/helpers/backend/gql/queries/GetCollectionChildrenIDs.graphql:3:22
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 1.8s at /root/hoppscotch/packages/hoppscotch-app
 ELIFECYCLE  Command failed with exit code 1.

```

![image](https://user-images.githubusercontent.com/87641643/236189780-180f3988-652e-415f-a145-14b572cf7950.png)

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment]
@fti-sfuke You seem to attaching to an old version of the codebase, can you pull the latest main (or release 2023.4.1) and see if it fixes your issues ?

**Comment by fti-sfuke** [comment]
Hi @AndrewBastin Thanks for the response.
> You seem to attaching to an old version of the codebase, can you pull the latest main (or release 2023.4.1)

Now, I tried to pull the latest `main` as well as the new release tag `2023.4.1."

But this time, it failed here.hoppscotch-backend@2023.4.1 generate-gql-sdl /root/samadhan/hoppscotch/packages/hoppscotch-backend
![image](https://user-images.githubusercontent.com/87641643/236405592-31cd1240-cddc-454f-a2bd-09287b799bdb.png)

Here is the complete result.

```
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# git checkout 2023.4.1
Note: checking out '2023.4.1'.
HEAD is now at 8450fb65 chore: release 2023.4.1

```

```
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# git branch
* (HEAD detached at 2023.4.1)
  main
```

```
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# npm install -g pnpm

changed 1 package, and audited 2 packages in 708ms
1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# pnpm install
Scope: all 10 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2366
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Downloading registry.npmjs.org/typescript/4.8.4: 11.9 MB/11.9 MB, done
Downloading registry.npmjs.org/typescript/4.9.3: 11.6 MB/11.6 MB, done
Progress: resolved 2366, reused 1639, downloaded 673, added 2366, done
 WARN  Local dependency not found at /root/samadhan/hoppscotch/packages/hoppscotch-backend/@types/nestjs/jwt
node_modules/.pnpm/@prisma+engines@4.8.1/node_modules/@prisma/engines: Running postinstall script...
node_modules/.pnpm/@prisma+engines@4.8.1/node_modules/@prisma/engines: Running postinstall script, done in 1s
node_modules/.pnpm/@apollo+protobufjs@1.2.6/node_modules/@apollo/protobufjs: Running postinstall script, done in 39ms
node_modules/.pnpm/@apollo+protobufjs@1.2.7/node_modules/@apollo/protobufjs: Running postinstall script, done in 63mss@7.6.0/node_modulnode_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modulnode_modules/.pnpm/argon2@0.30.3/node_modules/argon2: Running install script, done in 21.3s
node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt: Running install script, done in 5.6s
node_modules/.pnpm/core-js@3.26.0/node_modules/core-js: Running postinstall script, done in 46ms
node_modules/.pnpm/protobufjs@6.11.3/node_modules/protobufjs: Running postinstall script, done in 39ms
node_modules/.pnpm/vue-demi@0.13.1_vue@3.2.37/node_modules/vue-demi: Running postinstall script, done in 102ms
node_modules/.pnpm/vue-demi@0.13.1_vue@3.2.45/node_modules/vue-demi: Running postinstall script, done in 82ms
node_modules/.pnpm/esbuild@0.15.15/node_modules/esbuild: Running postinstall script, done in 60ms
node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild: Running postinstall script, done in 64ms
node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild: Running postinstall script, done in 72ms
node_modules/.pnpm/prisma@4.8.1/node_modules/prisma: Running preinstall script, done in 65ms
node_modules/.pnpm/prisma@4.8.1/node_modules/prisma: Running install script, done in 45ms
node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client: Running postinstall script, done in 572ms

dependencies:
+ husky 7.0.4
+ lint-staged 12.5.0

devDependencies:
+ @commitlint/cli 16.3.0
+ @commitlint/config-conventional 16.2.4
+ @types/node 17.0.45
+ cross-env 7.0.3
+ http-server 14.1.1

packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run:
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│ 
│ src/index.js → dist/index.cjs, ./dist...
│ created dist/index.cjs, ./dist in 1.7s
└─ Running...
└─ Done in 2.5sotch-backend postinstall$ prisma generate && pnpm run generate-gql-sdl
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (4.8.1 | library) to ./../../node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/cl
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
[1 lines collapsed]
│ > cross-env GQL_SCHEMA_EMIT_LOCATION='../../../gql-gen/backend-schema.gql' GENERATE_GQL_SCHEMA=true WHITELISTED_ORIGINS='' nest sta
│ /root/samadhan/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21
└─ Running...
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code /root/samadhan/hoppscotch/packages/hoppscotch-data
│ > vite build
│ vite v3.2.4 building for production...
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (4.8.1 | library) to ./../../node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/cl
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
│ > hoppscotch-backend@2023.4.1 generate-gql-sdl /root/samadhan/hoppscotch/packages/hoppscotch-backend
│ > cross-env GQL_SCHEMA_EMIT_LOCATION='../../../gql-gen/backend-schema.gql' GENERATE_GQL_SCHEMA=true WHITELISTED_ORIGINS='' nest sta
│ /root/samadhan/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21
│   throw new Error(errMessage);
│         ^
│ Error: mailer/smtp_url_undefined
│     at throwErr (/root/samadhan/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21:9)
│     at Object.<anonymous> (/root/samadhan/hoppscotch/packages/hoppscotch-backend/src/mailer/mailer.module.ts:15:48)
│     at Module._compile (node:internal/modules/cjs/loader:1103:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
│     at Module.load (node:internal/modules/cjs/loader:981:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
│     at Module.require (node:internal/modules/cjs/loader:1005:19)
│     at require (node:internal/modules/cjs/helpers:102:18)ere are some inertnal bugs.
│     at Object.<anonymous> (/root/samadhan/hoppscotch/packages/hoppscotch-backend/src/auth/auth.module.ts:5:1)
│     at Module._compile (node:internal/modules/cjs/loader:1103:14)
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 9.4s at /root/samadhan/hoppscotch/packages/hoppscotch-backend
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code /root/samadhan/hoppscotch/packages/hoppscotch-data
│ > vite build
│ vite v3.2.4 building for production...
│ transforming...
│ ✓ 287 modules transformed.d
│ rendering chunks...
│ dist/hoppscotch-data.js   46.28 KiB / gzip: 13.39 KiB
│ dist/hoppscotch-data.cjs   34.28 KiB / gzip: 12.04 KiB
│ > @hoppscotch/data@0.4.4 build:decl /root/samadhan/hoppscotch/packages/hoppscotch-data
│ > tsc --project tsconfig.decl.json
└─ Done in 4.2s
packages/hoppscotch-ui postinstall$ pnpm run build
[2 lines collapsed]
│ vite v3.2.4 building for production...
│ transforming...
│ [vite:dts] A error occurred when transform code, maybe there are some inertnal bugs.
│ ✓ 730 modules transformed.
│ rendering chunks...
│ dist/style.css     41.85 KiB / gzip: 5.43 KiB
│ dist/index.es.js   201.98 KiB / gzip: 44.85 KiB
│ dist/index.es.js.map 810.10 KiB
│ [vite:dts] Start generate declaration files...
│ [vite:dts] Declaration files built in 3198ms.
└─ Done in 9.2s
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 86ms
 ELIFECYCLE  Command failed with exit code 1.

**Comment by fti-sfuke** [comment]
**Here is the complete result of  main branch codebase.**

```
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'. 

```

```
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# npm install -g pnpm

changed 1 package, and audited 2 packages in 613ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

```
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# pnpm install
Scope: all 10 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
 WARN  Local dependency not found at /root/samadhan/hoppscotch/packages/hoppscotch-backend/@types/nestjs/jwt
packages/hoppscotch-backend postinstall$ prisma generate && pnpm run generate-gql-sdl
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (4.8.1 | library) to ./../../node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/cl
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
│ > hoppscotch-backend@2023.4.1 generate-gql-sdl /root/samadhan/hoppscotch/packages/hoppscotch-backend
│ > cross-env GQL_SCHEMA_EMIT_LOCATION='../../../gql-gen/backend-schema.gql' GENERATE_GQL_SCHEMA=true WHITELISTED_ORIGINS='' nest sta
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run:
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│ /root/samadhan/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run:
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[1 lines collapsed]
│ src/index.js → dist/index.cjs, ./dist...
│ created dist/index.cjs, ./dist in 1.6s
└─ Done in 2.5s
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code /root/samadhan/hoppscotch/packages/hoppscotch-data
│ > vite build
│ vite v3.2.4 building for production...oot/samadhan/hoppscotch/packages/hoppscotch-data
│ transforming...
│ ✓ 287 modules transformed.
│   throw new Error(errMessage);
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run:hoppscotch/packages/hoppscotch-data
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (4.8.1 | library) to ./../../node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/cl
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
│ > hoppscotch-backend@2023.4.1 generate-gql-sdl /root/samadhan/hoppscotch/packages/hoppscotch-backend
│ > cross-env GQL_SCHEMA_EMIT_LOCATION='../../../gql-gen/backend-schema.gql' GENERATE_GQL_SCHEMA=true WHITELISTED_ORIGINS='' nest sta
│ /root/samadhan/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21
│   throw new Error(errMessage);
│         ^
│ Error: mailer/smtp_url_undefined
│     at throwErr (/root/samadhan/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21:9)
│     at Object.<anonymous> (/root/samadhan/hoppscotch/packages/hoppscotch-backend/src/mailer/mailer.module.ts:15:48)
│     at Module._compile (node:internal/modules/cjs/loader:1103:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
│     at Module.load (node:internal/modules/cjs/loader:981:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
│     at Module.require (node:internal/modules/cjs/loader:1005:19)
│     at require (node:internal/modules/cjs/helpers:102:18)
│     at Object.<anonymous> (/root/samadhan/hoppscotch/packages/hoppscotch-backend/src/auth/auth.module.ts:5:1)
│     at Module._compile (node:internal/modules/cjs/loader:1103:14)
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 8.4s at /root/samadhan/hoppscotch/packages/hoppscotch-backend
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run:
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│ 
│ src/index.js → dist/index.cjs, ./dist...
│ created dist/index.cjs, ./dist in 1.6s
└─ Done in 2.5s
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code /root/samadhan/hoppscotch/packages/hoppscotch-data
│ > vite build
│ vite v3.2.4 building for production...
│ transforming...
│ ✓ 287 modules transformed.
│ dist/hoppscotch-data.js   46.28 KiB / gzip: 13.39 KiB
│ dist/hoppscotch-data.cjs   34.28 KiB / gzip: 12.04 KiB
│ > @hoppscotch/data@0.4.4 build:decl /root/samadhan/hoppscotch/packages/hoppscotch-data
│ > tsc --project tsconfig.decl.json
└─ Done in 4.2s
packages/hoppscotch-ui postinstall$ pnpm run build
[1 lines collapsed]
│ > vite build
│ vite v3.2.4 building for production...
│ transforming...
│ [vite:dts] A error occurred when transform code, maybe there are some inertnal bugs.
│ ✓ 730 modules transformed.
│ rendering chunks...
│ dist/style.css     41.85 KiB / gzip: 5.43 KiB
│ dist/index.es.js   201.98 KiB / gzip: 44.85 KiB
│ dist/index.es.js.map 810.10 KiB
│ [vite:dts] Start generate declaration files...
└─ Running...
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 92ms
 ELIFECYCLE  Command failed with exit code 1.
root@DEB-NUC11PAH-G6PA2500045B:~/samadhan/hoppscotch# 

```

**Comment by liyasthomas** [comment]
Hi @fti-sfuke, ensure you're following the [prerequisites](https://docs.hoppscotch.io/documentation/self-host/prerequisites) for self-hosting Hoppscotch.
For more info, refer to the [documentation on self-hosting](https://docs.hoppscotch.io/documentation/self-host/getting-started). The installation section describes the required environment configuration. Kindly share your masked `.env` file while you report an issue in the self-hosting environment.

**Comment by fti-sfuke** [comment]
Hi @liyasthomas 
The above issue is resolved after updating the.env.example file from the root directory to the.env file. 
Thanks for the support ! 
I am able to successfully setup a local development environment with the following steps:

   1. Clone the repo 
   2. Install pnpm using npm by running npm install -g pnpm
    `npm install -g pnpm`
   3. Install vite build tool in project:
    `npm install -g vite`
  4. Set node_modules/.bin directory is PATH environment variable
    `export PATH="./node_modules/.bin:$PATH"`
5. Updating the`.env.example` file from the root dir as `.env`
    `mv .env.example .env`
6. Install pnpm before build
    `pnpm install`
7. Checkout ` hoppscotch/packages/hoppscotch-selfhost-web/ `
8.   Build a packages
    `npm run build`
9. Start the server
    `pnpm start`
10. Open the development site by going to http://localhost:3000/ in your browser.
