### ISSUE TITLE
[bug]: SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'clearRequireCache'

### ISSUE THREAD

**Issue by fti-sfuke** [hoppscotch/hoppscotch#3035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
**Local development environment:** 

- Checkout `v2.2.0`
- Install pnpm using npm by running npm install -g pnpm. ( OK )
- Install dependencies by running pnpm install within the directory ( OK )
- Start the development server with pnpm run dev. ( ERROR )

**Environment details :**

OS Detail : 
```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# 

```
**Node Version and npm version :** 

```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# node -v
v16.14.2
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# npm -v
8.5.0

```

### Steps to reproduce

- Checkout `v2.2.0`
```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# git branch
* (HEAD detached at v2.2.0)
  main

```

- Install pnpm using npm by running npm install -g pnpm. ( OK )

```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# npm install -g pnpm
changed 1 package, and audited 2 packages in 568ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

- Install dependencies by running pnpm install within the directory ( OK )

```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# pnpm install
Scope: all 5 workspace projects
Downloading registry.npmjs.org/typescript/4.5.5: 11.3 MB/11.3 MB, done
Downloading registry.npmjs.org/firebase/9.6.4: 5.55 MB/5.55 MB, done
packages/hoppscotch-app                  |  WARN  deprecated har-validator@5.1.5
packages/hoppscotch-app                  |  WARN  deprecated xmldom@0.1.31
packages/hoppscotch-app                  |  WARN  deprecated vue-analytics@5.22.1
Downloading registry.npmjs.org/typescript/4.2.4: 10.4 MB/10.4 MB, done
packages/hoppscotch-app                  |  WARN  deprecated popper.js@1.16.1
packages/hoppscotch-app                  |  WARN  deprecated mkdirp-promise@1.1.0
packages/hoppscotch-app                  |  WARN  deprecated urix@0.1.0
packages/hoppscotch-app                  |  WARN  deprecated resolve-url@0.2.1
packages/hoppscotch-app                  |  WARN  deprecated @types/browserslist@4.15.0
packages/hoppscotch-app                  |  WARN  deprecated @types/anymatch@3.0.0
packages/hoppscotch-app                  |  WARN  deprecated svgo@1.3.2
packages/hoppscotch-app                  |  WARN  deprecated core-js@2.6.12
packages/hoppscotch-app                  |  WARN  deprecated querystring@0.2.1
packages/hoppscotch-app                  |  WARN  deprecated chokidar@2.1.8
packages/hoppscotch-app                  |  WARN  deprecated fsevents@1.2.13
packages/hoppscotch-app                  |  WARN  deprecated querystring@0.2.0
packages/hoppscotch-app                  |  WARN  deprecated flatten@1.0.3
Packages: +1879 -699
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------
Progress: resolved 2483, reused 659, downloaded 1785, added 1828, done
node_modules/.pnpm/deasync@0.1.23/node_modules/deasync: Running install script, done in 180ms
node_modules/.pnpm/core-js@3.20.3/node_modules/core-js: Running postinstall script, done in 70ms
node_modules/.pnpm/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 93ms
node_modules/.pnpm/esbuild@0.12.29/node_modules/esbuild: Running postinstall script...
node_modules/.pnpm/esbuild@0.12.29/node_modules/esbuild: Running postinstall script, done in 1.6s
node_modules/.pnpm/@sentry+cli@1.71.0/node_modules/@sentry/cli: Running install script, done in 531ms5/node_modules/nuxt: Running postinode_modules/.pnpm/nuxt@2.15.8_babel-core@7.0.0-bridge.0_consola@3.1.0_mustache@4.2.0_typescript@4.5.5/node_modules/nuxt: Running postinstall script, done in 219mss@6.11.2/node_modules/protobufjs: Running postinstall script, done in 58ms
node_modules/.pnpm/esbuild@0.14.10/node_modules/esbuild: Running postinstall script, done in 52ms
node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild: Running postinstall script, done in 57ms
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run:
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│ 
│ src/index.js → dist/index.cjs, ./dist...
│ created dist/index.cjs, ./dist in 1.7s
└─ Done in 2.3s
packages/hoppscotch-data prepare$ tsup src --dts
[20 lines collapsed]
│ CJS dist/chunk-JUWXSDKJ.js     1010.00 B
│ DTS Build start
│ DTS ⚡️ Build success in 1314ms
│ DTS dist/index.d.ts              714.00 B
│ DTS dist/rest/index.d.ts         2.13 KB
│ DTS dist/graphql/index.d.ts      568.00 B
│ DTS dist/collection/index.d.ts   1.27 KB
│ DTS dist/rest/content-types.d.ts 462.00 B
│ DTS dist/rest/HoppRESTAuth.d.ts  853.00 B
│ DTS dist/type-utils.d.d.ts       1.00 B
└─ Done in 1.8s
packages/hoppscotch-js-sandbox postinstall$ pnpm run build
│ > @hoppscotch/js-sandbox@1.0.0 build /root/hoppscotch/packages/hoppscotch-js-sandbox
│ > npx tsc
└─ Done in 4s
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 92ms
packages/hoppscotch-app postinstall$ pnpm run gql-codegen
[14 lines collapsed]
│ [21:48:18] Load GraphQL documents [started]
│ [21:48:18] Load GraphQL documents [completed]
│ [21:48:18] Generate [started]
│ [21:48:19] Generate [completed]
│ [21:48:19] Generate helpers/backend/backend-schema.json [completed]
│ [21:48:19] Load GraphQL documents [completed]
│ [21:48:19] Generate [started]
│ [21:48:19] Generate [completed]
│ [21:48:19] Generate helpers/backend/graphql.ts [completed]
│ [21:48:19] Generate outputs [completed]
└─ Done in 2.1s

dependencies:
+ husky 7.0.4
+ lint-staged 12.3.1

devDependencies:
+ @commitlint/cli 16.1.0
+ @commitlint/config-conventional 16.0.0
+ @types/node 17.0.10
- jshint 2.10.2

 WARN  Issues with peer dependencies found
packages/hoppscotch-app
├─┬ @nuxtjs/eslint-config-typescript 8.0.0
│ └─┬ @nuxtjs/eslint-config 8.0.0
│   ├─┬ eslint-config-standard 16.0.3
│   │ └── ✕ unmet peer eslint@^7.12.1: found 8.7.0
│   └─┬ eslint-plugin-promise 5.1.1
│     └── ✕ unmet peer eslint@^7.0.0: found 8.7.0
├─┬ @nuxtjs/eslint-module 3.0.2
│ └─┬ eslint-webpack-plugin 2.5.4
│   └── ✕ unmet peer eslint@^7.0.0: found 8.7.0
└─┬ nuxt 2.15.8
  └─┬ @nuxt/builder 2.15.8
    └─┬ @nuxt/webpack 2.15.8
      └─┬ vue-loader 15.9.8
        └─┬ @vue/component-compiler-utils 3.3.0
          └─┬ consolidate 0.15.1
            ├── ✕ unmet peer mustache@^3.0.0: found 4.2.0
            └── ✕ unmet peer babel-core@^6.26.3: found 7.0.0-bridge.0

The integrity of 13581 files was checked. This might have caused installation to take longer.
Done in 42.6s
```

- Start the development server with pnpm run dev. ( ERROR ) 
```
root@DEB-NUC11PAH-G6PA2500045B:~/hoppscotch# pnpm run dev

> hoppscotch-app@2.2.0 dev /root/hoppscotch
> pnpm -r do-dev

Scope: 4 of 5 workspace projects
packages/hoppscotch-app do-dev$ pnpm run dev
│ > hoppscotch-app@2.2.0 dev /root/hoppscotch/packages/hoppscotch-app
│ > pnpx npm-run-all -p -l dev:*
│ .../share/pnpm/store/v3/tmp/dlx-17807    | Progress: resolved 1, reused 0, downloaded 0, added 0
│ .../share/pnpm/store/v3/tmp/dlx-17807    |  +93 +++++++++
│ .../share/pnpm/store/v3/tmp/dlx-17807    | Progress: resolved 93, reused 66, downloaded 27, added 93, done
│ [dev:nuxt       ] 
│ [dev:nuxt       ] > hoppscotch-app@2.2.0 dev:nuxt /root/hoppscotch/packages/hoppscotch-app
│ [dev:nuxt       ] > nuxt
│ [dev:nuxt       ] 
│ [dev:gql-codegen] 
│ [dev:gql-codegen] > hoppscotch-app@2.2.0 dev:gql-codegen /root/hoppscotch/packages/hoppscotch-app
│ [dev:gql-codegen] > graphql-codegen --config gql-codegen.yml --watch
│ [dev:gql-codegen] 
│ [dev:nuxt       ] 
│ [dev:nuxt       ]  FATAL  The requested module '@nuxt/kit' does not provide an export named 'clearRequireCache'
│ [dev:nuxt       ] 
│ [dev:nuxt       ]   import { resolveModule, defineNuxtModule, clearRequireCache, isNuxt3, isNuxt2, tryRequireModule, requireModule,
│ [dev:nuxt       ]   ^^^^^^^^^^^^^^^^^
│ [dev:nuxt       ]   SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'clearRequireCache'
│ [dev:nuxt       ]   at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
│ [dev:nuxt       ]   at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
│ [dev:nuxt       ]   at async Promise.all (index 0)
│ [dev:nuxt       ]   at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
│ [dev:nuxt       ]   at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
│ [dev:nuxt       ]   at async ModuleContainer.addModule (/root/hoppscotch/node_modules/.pnpm/@nuxt+core@2.15.8/node_modules/@nuxt/co
│ [dev:nuxt       ]   at async ModuleContainer.ready (/root/hoppscotch/node_modules/.pnpm/@nuxt+core@2.15.8/node_modules/@nuxt/core/d
│ [dev:nuxt       ]   at async Nuxt._init (/root/hoppscotch/node_modules/.pnpm/@nuxt+core@2.15.8/node_modules/@nuxt/core/dist/core.js
│ [dev:nuxt       ] 
│ [dev:nuxt       ] 
│ [dev:nuxt       ] ╭──────────────────────────────────────────────────────────────────────────────╮│                                
│ [dev:nuxt       ] 
│ [dev:nuxt       ]  ELIFECYCLE  Command failed with exit code 1.
│ [dev:gql-codegen] [21:48:36] Parse configuration [started]
│ [dev:gql-codegen] [21:48:36] Parse configuration [completed]
│ [dev:gql-codegen] [21:48:36] Generate outputs [started]
│ [dev:gql-codegen] [21:48:36] Generate helpers/backend/graphql.ts [started]
│ [dev:gql-codegen] [21:48:36] Generate helpers/backend/backend-schema.json [started]
│ [dev:gql-codegen] [21:48:36] Load GraphQL schemas [started]
│ [dev:gql-codegen] [21:48:36] Load GraphQL schemas [started]
│ [dev:gql-codegen] (node:17898) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
│ [dev:gql-codegen] (Use `node --trace-warnings ...` to show where the warning was created)
│ [dev:gql-codegen] [21:48:36] Load GraphQL schemas [completed]
│ [dev:gql-codegen] [21:48:36] Load GraphQL schemas [completed]
│ [dev:gql-codegen] [21:48:36] Load GraphQL documents [started]
│ [dev:gql-codegen] [21:48:36] Load GraphQL documents [started]
│ [dev:gql-codegen] [21:48:36] Load GraphQL documents [completed]
│ [dev:gql-codegen] [21:48:36] Generate [started]
│ [dev:gql-codegen] [21:48:36] Generate [completed]
│ [dev:gql-codegen] [21:48:36] Generate helpers/backend/backend-schema.json [completed]
│ [dev:gql-codegen] [21:48:37] Load GraphQL documents [completed]
│ [dev:gql-codegen] [21:48:37] Generate [started]
│ [dev:gql-codegen] [21:48:37] Generate [completed]
│ [dev:gql-codegen] [21:48:37] Generate helpers/backend/graphql.ts [completed]
│ [dev:gql-codegen] [21:48:37] Generate outputs [completed]
│ [dev:gql-codegen]   ℹ Watching for changes...
│ [dev:gql-codegen]   Shutting down watch...
│ [dev:gql-codegen]  ELIFECYCLE  Command failed.
│ ERROR: "dev:nuxt" exited with 1.
│  ERROR  Command failed with exit code 1: npm-run-all -p -l dev:*
│ pnpm: Command failed with exit code 1: npm-run-all -p -l dev:*
│     at makeError (/root/.nvm/versions/node/v16.14.2/lib/node_modules/pnpm/dist/pnpm.cjs:24466:17)
│     at handlePromise (/root/.nvm/versions/node/v16.14.2/lib/node_modules/pnpm/dist/pnpm.cjs:25037:33)
│     at runMicrotasks (<anonymous>)
│     at processTicksAndRejections (node:internal/process/task_queues:96:5)
│     at async Object.handler [as dlx] (/root/.nvm/versions/node/v16.14.2/lib/node_modules/pnpm/dist/pnpm.cjs:207600:7)
│     at async /root/.nvm/versions/node/v16.14.2/lib/node_modules/pnpm/dist/pnpm.cjs:216935:21
│     at async main (/root/.nvm/versions/node/v16.14.2/lib/node_modules/pnpm/dist/pnpm.cjs:216902:34)
│     at async runPnpm (/root/.nvm/versions/node/v16.14.2/lib/node_modules/pnpm/dist/pnpm.cjs:217157:5)
│     at async /root/.nvm/versions/node/v16.14.2/lib/node_modules/pnpm/dist/pnpm.cjs:217149:7
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 6.8s at /root/hoppscotch/packages/hoppscotch-app
/root/hoppscotch/packages/hoppscotch-app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  hoppscotch-app@2.2.0 do-dev: `pnpm run dev`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

```

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment]
@fti-sfuke This looks like an old version of the codebase, can you pull the latest and see if the issue still persists ?

**Comment by fti-sfuke** [comment]
Hi @AndrewBastin Thanks for the response. 
I tried to pull the latest `main` as well as the new release tag `2023.4.1`

But from the `2023.4.1` codebase its faild here.
hoppscotch-backend@2023.4.1 generate-gql-sdl /root/hoppscotch/packages/hoppscotch-backend

Here is the complete details : 
https://github.com/hoppscotch/hoppscotch/issues/3034#issuecomment-1535881873

https://github.com/hoppscotch/hoppscotch/issues/3034#issuecomment-1535893072

**Comment by liyasthomas** [comment]
Since the issue mentioned in this issue description is not reproducible, I'm closing this issue.

@fti-sfuke, kindly track your issue on #3034.
