### ISSUE TITLE
ReferenceError: AuthUser_1 is not defined [bug][self-hosted]: 

### ISSUE THREAD

**Issue by tzaqam** [hoppscotch/hoppscotch#3127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i ran: pnpm install throws an ReferenceError

│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
│ > hoppscotch-backend@2023.4.3 generate-gql-sdl C:\Users\tzaqam\Documents\developement\hoppscotch\packages\hoppscotch-backend
│ > cross-env GQL_SCHEMA_EMIT_LOCATION='../../../gql-gen/backend-schema.gql' GENERATE_GQL_SCHEMA=true WHITELISTED_ORIGINS='' nest start
│ C:\Users\tzaqam\Documents\developement\hoppscotch\packages\hoppscotch-backend\src\user\user.resolver.ts:29
│   me(@GqlUser() user: AuthUser) {
│                       ^g.decl.jsonip: 45.75 KiB
│ ReferenceError: AuthUser_1 is not defined
│     at Object.<anonymous> (C:\Users\tzaqam\Documents\developement\hoppscotch\packages\hoppscotch-backend\src\user\user.resolver.ts:29:23)
│     at Module._compile (node:internal/modules/cjs/loader:1254:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
│     at Module.load (node:internal/modules/cjs/loader:1117:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
│     at Module.require (node:internal/modules/cjs/loader:1141:19) some inertnal bugs.
│     at require (node:internal/modules/cjs/helpers:110:18)
│     at Object.<anonymous> (C:\Users\tzaqam\Documents\developement\hoppscotch\packages\hoppscotch-backend\src\user\user.module.ts:2:1)
│     at Module._compile (node:internal/modules/cjs/loader:1254:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 20s at C:\Users\tzaqam\Documents\developement\hoppscotch\packages\hoppscotch-backend
 ELIFECYCLE  Command failed with exit code 1.

### Steps to reproduce

Install all prerequesites for self-hosted
1.- pnpm install

### Environment

Production

### Version

Self-hosted

**Comment by mirarifhasan** [comment]
Hi @tzaqam,

I attempted to reproduce the reported issue on my own computer, but I wasn't able to encounter it.

I kindly request you to pull the latest updates from the repository and give it another try. This should ensure that you have all the recent changes incorporated into your codebase. Once you've done that, please let me know if the issue persists or if any further assistance is needed.

Thank you!

**Comment by nguyennm96** [comment]
@mirarifhasan are you using chip M1 or intel?

**Comment by AndrewBastin** [comment]
Closing due to inactivity. Please reopen if you still have this issue in the 2023.8.0 release.

**Comment by liudonghua123** [comment]
Delete `packages/hoppscotch-backend/dist` works for me. However, I got another error `Error: mailer/smtp_url_undefined`. Maybe I need to delete `node_modules` and try again.

```
D:\code\rust\hoppscotch-app\hoppscotch>pnpm install
Scope: all 11 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-data
│ > vite build
│ vite v3.2.4 building for production...
│ transforming...
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ ✓ 287 modules transformed.
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ rendering chunks...
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ dist/hoppscotch-data.js   46.28 KiB / gzip: 13.39 KiB
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ dist/hoppscotch-data.cjs   34.28 KiB / gzip: 12.04 KiB
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ > @hoppscotch/data@0.4.4 build:decl D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-data
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ > tsc --project tsconfig.decl.json
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
└─ Running...
packages/dioc prepare$ pnpm run build
[5 lines collapsed]
│ Browserslist: caniuse-lite is outdated. Please run:
└─ Running...
packages/dioc prepare$ pnpm run buildB │ gzip: 0.24 kB
[5 lines collapsed]
│   npx browserslist@latest --update-db
└─ Running...
packages/dioc prepare$ pnpm run buildB │ gzip: 0.24 kBBapp\hoppscotch\packages\hoppscotch-uiHEMA=true WHITELISTED_ORI…
[5 lines collapsed]
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
└─ Running...
packages/dioc prepare$ pnpm run buildB │ gzip: 0.24 kBB
[5 lines collapsed]
│
└─ Running...
packages/dioc prepare$ pnpm run buildB │ gzip: 0.24 kBB
[5 lines collapsed]
│ src/index.js → dist/index.cjs, ./dist...
└─ Running...
packages/dioc prepare$ pnpm run buildB │ gzip: 0.24 kBB
[5 lines collapsed]
│ created dist/index.cjs, ./dist in 3s
└─ Running...
packages/dioc prepare$ pnpm run buildB │ gzip: 0.24 kBB
[5 lines collapsed]
└─ Done in 24.1sks...
│ computing gzip size...
│ dist/vue.js                  0.33 kB │ gzip: 0.24 kBB
│ dist/testing.js              0.52 kB │ gzip: 0.33 kBB
│ dist/index.js                1.80 kB │ gzip: 0.77 kBBapp\hoppscotch\packages\hoppscotch-ui
│ dist/container-9dabdb69.js  16.60 kB │ gzip: 4.60 kB
│ dist/vue.cjs                  0.34 kB │ gzip: 0.26 kB
│ dist/testing.cjs              0.43 kB │ gzip: 0.32 kB
│ dist/index.cjs                1.25 kB │ gzip: 0.62 kBapp\hoppscotch\packages\hoppscotch-ui
│ dist/container-1fe4cc86.cjs  11.09 kB │ gzip: 3.64 kB..\node_modules\.pnpm\@prisma+client@4.16.2_prisma@4.16.2\node…
└─ Done in 16.6s
packages/hoppscotch-ui postinstall$ pnpm run build
[1 lines collapsed]
│ > vite buildPrisma Client (4.16.2 | library) to .\..\..\node_modules\.pnpm\@prisma+client@4.16.2_prisma@4.16.2\node…
│ vite v3.2.4 building for production...
│ transforming...
│ ✓ 741 modules transformed.
│ rendering chunks...
│ [vite:dts] Start generate declaration files...
│ dist/style.css     66.25 KiB / gzip: 7.96 KiB
│ dist/index.es.js   221.17 KiB / gzip: 48.96 KiB
│ dist/index.es.js.map 831.73 KiB
│ [vite:dts] Declaration files built in 11984ms.
└─ Done in 52s
packages/hoppscotch-backend postinstall$ prisma generate && pnpm run generate-gql-sdl
│ Prisma schema loaded from prisma\schema.prisma
│ ✔ Generated Prisma Client (4.16.2 | library) to .\..\..\node_modules\.pnpm\@prisma+client@4.16.2_prisma@4.16.2\node…
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
│ > hoppscotch-backend@2023.8.0 generate-gql-sdl D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend
│ > cross-env GQL_SCHEMA_EMIT_LOCATION='../../../gql-gen/backend-schema.gql' GENERATE_GQL_SCHEMA=true WHITELISTED_ORI…
│ D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend\src\utils.ts:27
│   throw new Error(errMessage);
│         ^
│ Error: mailer/smtp_url_undefined
│     at throwErr (D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend\src\utils.ts:27:9)
│     at Object.<anonymous> (D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend\src\mailer\mailer.mod…
│     at Module._compile (node:internal/modules/cjs/loader:1255:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
│     at Module.load (node:internal/modules/cjs/loader:1113:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
│     at Module.require (node:internal/modules/cjs/loader:1137:19)
│     at require (node:internal/modules/helpers:121:18)
│     at Object.<anonymous> (D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend\src\auth\auth.module.…
│     at Module._compile (node:internal/modules/cjs/loader:1255:14)
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 59.3s at D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 676ms
 ELIFECYCLE  Command failed with exit code 1.

D:\code\rust\hoppscotch-app\hoppscotch>
```

**Comment by liudonghua123** [comment]
I tried again and I have other errors.

<details><summary>Details</summary>

```
D:\code\rust\hoppscotch-app\hoppscotch>pnpm install
Scope: all 11 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
packages/dioc prepare$ pnpm run build
│ > dioc@0.1.0 build D:\code\rust\hoppscotch-app\hoppscotch\packages\dioc
│ > vite build && tsc --emitDeclarationOnly
│ vite v4.0.4 building for production...
│ transforming...
└─ Running...
│ ✓ 229 modules transformed.nstall$ pnpm run build
└─ Running...
│ rendering chunks...i postinstall$ pnpm run build
└─ Running...
│ computing gzip size...ostinstall$ pnpm run build
└─ Running...
│ dist/vue.js                  0.33 kB │ gzip: 0.24 kB
└─ Running...
│ dist/testing.js              0.52 kB │ gzip: 0.33 kB
└─ Running...
│ dist/index.js                1.80 kB │ gzip: 0.77 kB
└─ Running...
[1 lines collapsed]                                                                                                                                                             │ > @hoppscotch/ui@0.0.1 build D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-ui
│ > vite buildirror-lang-graphql prepare$ rollup -cde && pnpm run build:decl
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -cde && pnpm run build:decl
└─ Running...
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-data
│ > vite build
│ vite v3.2.4 building for production...gzip: 13.39 KiB
│ dist/container-9dabdb69.js  16.60 kB │ gzip: 4.60 kB
└─ Running...
p5ckages/hoppscotch-ui postinstall$ pnpm run build
│ rendering chunks...
└─ Done in 43.7s size...
│ dist/vue.js                  0.33 kB │ gzip: 0.24 kB
│ dist/testing.js              0.52 kB │ gzip: 0.33 kB
│ Browserslist: caniuse-lite is outdated. Please run:B
│ vite v3.2.4 building for production...
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run: && pnpm run build:decl
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│
│ transforming...dist/index.cjs, ./dist...
└─ Running...
packages/codemirror-lang-graphql prepare$ rollup -c
│ Browserslist: caniuse-lite is outdated. Please run: && pnpm run build:decl
│   npx browserslist@latest --update-db
│   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
│
│ src/index.js → dist/index.cjs, ./dist...
│ created dist/index.cjs, ./dist in 2.6s
└─ Done in 1m 4s
packages/hoppscotch-data prepare$ pnpm run build:code && pnpm run build:decl
│ > @hoppscotch/data@0.4.4 build:code D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-data
│ > vite build
│ vite v3.2.4 building for production...
│ transforming...
│ ✓ 287 modules transformed.postinstall$ prisma generate && pnpm run generate-gql-sdl
│ rendering chunks...
│ dist/hoppscotch-data.js   46.28 KiB / gzip: 13.39 KiB
│ dist/hoppscotch-data.cjs   34.28 KiB / gzip: 12.04 KiB
│ > @hoppscotch/data@0.4.4 build:decl D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-data
│ > tsc --project tsconfig.decl.jsonsma/client'
└─ Done in 43.2s
packages/hoppscotch-backend postinstall$ prisma generate && pnpm run generate-gql-sdl
│ Prisma schema loaded from prisma\schema.prisma
│ ✔ Generated Prisma Client (4.16.2 | library) to .\..\..\node_modules\.pnpm\@prisma+client@4.16.2_prisma@4.16.2\node_modules\@prisma\client in 1.65s
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
│ > hoppscotch-backend@2023.8.1 generate-gql-sdl D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend
│ > cross-env GQL_SCHEMA_EMIT_LOCATION='../../../gql-gen/backend-schema.gql' GENERATE_GQL_SCHEMA=true WHITELISTED_ORIGINS='' nest start
│ src/team-collection/team-collection.service.ts:857:20 - error TS2339: Property 'teamCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 857           await tx.teamCollection.updateMany({
│                        ~~~~~~~~~~~~~~
│ src/team-collection/team-collection.service.ts:869:50 - error TS2339: Property 'teamCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 869           const updatedTeamCollection = await tx.teamCollection.update({
│                                                      ~~~~~~~~~~~~~~
│ src/team-collection/team-collection.service.ts:916:18 - error TS2339: Property 'teamCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 916         await tx.teamCollection.updateMany({
│                      ~~~~~~~~~~~~~~
│ src/team-collection/team-collection.service.ts:926:48 - error TS2339: Property 'teamCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 926         const updatedTeamCollection = await tx.teamCollection.update({
│                                                    ~~~~~~~~~~~~~~
│ src/team-request/team-request.service.ts:379:20 - error TS2339: Property 'teamRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 379           await tx.teamRequest.updateMany({
│                        ~~~~~~~~~~~
│ src/team-request/team-request.service.ts:389:20 - error TS2339: Property 'teamRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 389           await tx.teamRequest.updateMany({
│                        ~~~~~~~~~~~
│ src/team-request/team-request.service.ts:398:22 - error TS2339: Property 'teamRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 398             await tx.teamRequest.updateMany({
│                          ~~~~~~~~~~~
│ src/team-request/team-request.service.ts:416:41 - error TS2339: Property 'teamRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 416         const updatedRequest = await tx.teamRequest.update({
│                                             ~~~~~~~~~~~
│ src/team/team.service.ts:424:53 - error TS2339: Property 'teamID' does not exist on type 'unknown'.
│ 424             const res = await this.leaveTeam(member.teamID, uid);
│                                                         ~~~~~~
│ src/user-collection/user-collection.service.ts:692:20 - error TS2339: Property 'userCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 692           await tx.userCollection.updateMany({
│                        ~~~~~~~~~~~~~~
│ src/user-collection/user-collection.service.ts:704:50 - error TS2339: Property 'userCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 704           const updatedUserCollection = await tx.userCollection.update({
│                                                      ~~~~~~~~~~~~~~
│ src/user-collection/user-collection.service.ts:755:18 - error TS2339: Property 'userCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 755         await tx.userCollection.updateMany({
│                      ~~~~~~~~~~~~~~
│ src/user-collection/user-collection.service.ts:765:48 - error TS2339: Property 'userCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, Rejec…
│ 765         const updatedUserCollection = await tx.userCollection.update({
│                                                    ~~~~~~~~~~~~~~
│ src/user-request/user-request.service.ts:404:20 - error TS2339: Property 'userRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 404           await tx.userRequest.updateMany({
│                        ~~~~~~~~~~~
│ src/user-request/user-request.service.ts:414:20 - error TS2339: Property 'userRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 414           await tx.userRequest.updateMany({
│                        ~~~~~~~~~~~
│ src/user-request/user-request.service.ts:423:22 - error TS2339: Property 'userRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 423             await tx.userRequest.updateMany({
│                          ~~~~~~~~~~~
│ src/user-request/user-request.service.ts:441:41 - error TS2339: Property 'userRequest' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFou…
│ 441         const updatedRequest = await tx.userRequest.update({
│                                             ~~~~~~~~~~~
│ Found 17 error(s).
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 1m 18.7s at D:\code\rust\hoppscotch-app\hoppscotch\packages\hoppscotch-backend
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 518ms
 ELIFECYCLE  Command failed with exit code 1.

D:\code\rust\hoppscotch-app\hoppscotch>
```

</details> 

See also https://github.com/hoppscotch/hoppscotch/issues/3373.
