### ISSUE TITLE
[bug]: Hoppscotch CLI error

### ISSUE THREAD

**Issue by SaailN** [hoppscotch/hoppscotch#3289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was exploring ```hopp test ``` command to run the collection file(.json) exported from hoppscotch.io but getting the following error while running the file.
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /usr/local/lib/node_modules/@hoppscotch/cli/dist/index.js
- /usr/local/lib/node_modules/@hoppscotch/cli/bin/hopp
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoppscotch/cli/dist/index.js:24118:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@hoppscotch/cli/dist/index.js',
    '/usr/local/lib/node_modules/@hoppscotch/cli/bin/hopp'
  ]
}
```

### Steps to reproduce

![Screenshot from 2023-08-24 19-59-27](https://github.com/hoppscotch/hoppscotch/assets/40292489/fb50693f-935b-4e55-9881-e894b2584181)

### Environment

Production

### Version

Cloud

**Comment by nivedin** [comment]
@SaailN can you try renaming the file name and run the test.

**Comment by AndrewBastin** [comment]
@SaailN can we also get your node version and OS info ?

**Comment by krystian-dziedziola-olx** [comment]
I had a similar problem and using the latest Node version fixed it. 

I was using an old version of the Node because of the requirements of a project. If you're in a similar situation, you can use [nvm](https://github.com/nvm-sh/nvm) to keep multiple versions of the Node.

**Comment by KrystianDziedziola** [comment]
I had a similar problem and using the latest Node version fixed it. 

I was using an old version of the Node because of the requirements of a project. If you're in a similar situation, you can use [nvm](https://github.com/nvm-sh/nvm) to keep multiple versions of the Node.

**Comment by jamesgeorge007** [comment]
@SaailN, can you try with the latest version of the CLI? Please ensure the Node.js version is at least `v18`.
