### ISSUE TITLE
[bug]: Hard trouble with refreshing and admin dashboard. Software is not usable. 

### ISSUE THREAD

**Issue by pthoelken** [hoppscotch/hoppscotch#3349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We're getting hard in trouble with the whole Hoppscotch application because we have to refreshing all pages a lot till it works.  This behavior is coming up on all computers and browsers in our team. We're working in a self-hosted environment behind a reverse proxy (apache). Check the configuration below. 

**Apache Configuration Snippet**
```
<VirtualHost *:80>

    DocumentRoot    /var/www/html
    ServerName      my-server-url
    ServerAdmin     root@localhost

    ErrorLog        /var/log/apache2/ssl_error_hoppscotch.log
    TransferLog     /var/log/apache2/ssl_access_hoppscotch.log
    CustomLog       /var/log/apache2/ssl_access_hoppscotch.log combined

    RewriteEngine on
    <Location />
        Order allow,deny
        Allow from all
    </Location>

    RewriteRule ^/(.*)$ https://my-server-url/$1 [L]
</VirtualHost>


<VirtualHost *:443>
    DocumentRoot    /var/www/html
    ServerName      my-server-url
    ServerAdmin     root@localhost

    ErrorLog        /var/log/apache2/ssl_error_hoppscotch.log
    TransferLog     /var/log/apache2/ssl_access_hoppscotch.log
    CustomLog       /var/log/apache2/ssl_access_hoppscotch.log combined

    SSLProxyEngine on
    SSLEngine On
    SSLCertificateFile      /etc/apache2/ssl/certificate.pem
    SSLCertificateKeyFile   /etc/apache2/ssl/certificate.key

    RewriteEngine on
    ProxyPreserveHost On
    ProxyRequests off
    ProxyVia on

    <Location />
        Order allow,deny
        Allow from all
    </Location>

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Prot "443"
    SetEnvIf Origin "https://(my-server-url|my-server-url:8443)$" AccessControlAllowOrigin=$0
    Header set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e

    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /backend/graphql(.*) ws://127.0.0.1:3170/graphql$1 [P,L]

    RewriteRule ^/my-server-url$ http://my-server-url [L]

    ProxyPass         /backend/  http://127.0.0.1:3170/
    ProxyPassReverse  /backend/  http://127.0.0.1:3170/
    ProxyPass         /  http://127.0.0.1:3000/
    ProxyPassReverse  /  http://127.0.0.1:3000/

</VirtualHost>


Listen 8443
<VirtualHost *:8443>

    DocumentRoot    /var/www/html
    ServerName      my-server-url
    ServerAdmin     root@localhost

    ErrorLog        /var/log/apache2/ssl_error_hoppscotch.log
    TransferLog     /var/log/apache2/ssl_access_hoppscotch.log
    CustomLog       /var/log/apache2/ssl_access_hoppscotch.log combined

    SSLProxyEngine on
    SSLEngine On
    SSLCertificateFile      /etc/apache2/ssl/certificate.pem
    SSLCertificateKeyFile   /etc/apache2/ssl/certificate.key

    RewriteEngine on
    ProxyPreserveHost On
    ProxyRequests off
    ProxyVia on

    <Location />
        Order allow,deny
        Allow from all
    </Location>

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Prot "443"
    SetEnvIf Origin "https://(my-server-url|my-server-url:8443)$" AccessControlAllowOrigin=$0
    Header set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e

    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /backend/graphql(.*) ws://127.0.0.1:3170/graphql$1 [P,L]

    ProxyPass         /backend/  http://127.0.0.1:3170/
    ProxyPassReverse  /backend/  http://127.0.0.1:3170/
    ProxyPass         /  http://127.0.0.1:3100/
    ProxyPassReverse  /  http://127.0.0.1:3100/
</VirtualHost>
```

### Steps to reproduce

**Users Dashboard**
1. Go to the website
2. Click on "login"
3. Choose only available option "Microsoft"
4. I will be instantly redirected to "https://my-server-url/backend/v1/auth/microsoft" which shows me the "Hoppscotch 404 page". 
5. Just after clicking "Shift + Cmd + R" (for refresh without cache) I will be redirected to the Azure Active directory page.
6. After login into the azure AD I've been redirected to the callback address like "https://my-server-url/backend/v1/auth/microsoft/callback?code=XYZ" which shows me the "Hoppscotch 404 page". 
7. After refreshing this page here with "Shift + Cmd + R" the page shows me internal server error. 

After some refreshing and manual navigating to https://my-server-url and also refreshing the pages shows me as logged in and I can see my profile and workspaces.

**Admin Dashboard**
No more words needed I think :) also here the refreshing trouble!

![image](https://github.com/hoppscotch/hoppscotch/assets/12643853/8f9c79c7-f3f6-4d30-84a3-7e58dc151251)

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment]
@pthoelken Could you share the server logs with us when you encounter the `404` or `Internal server errors`?

**Comment by pthoelken** [comment]
For now I can't reproduce the "internal server error". Otherwise you can give me a path where the logs are saved into the container. I can fetch the logs from it and post it here.

**Comment by pthoelken** [comment]
For case in 404, I've reproduce this right now, but I can't see any logs in "docker-compose logs -f" while the 404.

**Comment by pthoelken** [comment]
The only docker-compose logs entries, what I get sometimes is this following. But the refresh struggle was also there before I got this error below. 

```
hoppscotchdb      | 2023-09-13 09:30:49.482 CEST [42] ERROR:  duplicate key value violates unique constraint "UserSettings_userUid_key"
hoppscotchdb      | 2023-09-13 09:30:49.482 CEST [42] DETAIL:  Key ("userUid")=(clmhfa3w40003nswuw3z5j80j) already exists.
hoppscotchdb      | 2023-09-13 09:30:49.482 CEST [42] STATEMENT:  INSERT INTO "public"."UserSettings" ("id","userUid","properties","updatedOn") VALUES ($1,$2,$3,$4) RETURNING "public"."UserSettings"."id"
hoppscotch-aio    | Backend Server | [Nest] 66  - 09/13/2023, 7:30:49 AM   ERROR [ExceptionsHandler] user_settings/settings_already_exists
hoppscotch-aio    | Backend Server | Error: user_settings/settings_already_exists
hoppscotch-aio    | Backend Server |     at throwErr (/usr/src/app/packages/hoppscotch-backend/dist/utils.js:14:11)
hoppscotch-aio    | Backend Server |     at UserSettingsResolver.createUserSettings (/usr/src/app/packages/hoppscotch-backend/dist/user-settings/user-settings.resolver.js:36:34)
hoppscotch-aio    | Backend Server |     at async target (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
hoppscotch-aio    | Backend Server |     at async Object.createUserSettings (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
hoppscotch-aio    | Backend Server | Query Complexity: 7

```

**Comment by pthoelken** [comment]
@balub  We're build this image manually by the [prod.Dockerfile](https://github.com/hoppscotch/hoppscotch/blob/release/2023.8.1/prod.Dockerfile) into the [branch 2023.8.1](https://github.com/hoppscotch/hoppscotch/tree/release/2023.8.1). The only file, what we're changed was this https://github.com/hoppscotch/hoppscotch/blob/release/2023.8.1/packages/hoppscotch-backend/src/mailer/mailer.module.ts because we have to change something for our mailserver (what works perfectly)

```
import { Module } from '@nestjs/common';
import { MailerModule as NestMailerModule } from '@nestjs-modules/mailer';
import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';
import { MailerService } from './mailer.service';
import { throwErr } from 'src/utils';
import {
  MAILER_FROM_ADDRESS_UNDEFINED,
  MAILER_SMTP_URL_UNDEFINED,
} from 'src/errors';

@Module({
  imports: [
    NestMailerModule.forRoot({
      transport: {
        host: process.env.MAILER_SMTP_ADDRESS,
        port: 25,
        ignoreTLS: true,
        secure: false,
      },
      defaults: {
        from:
          process.env.MAILER_ADDRESS_FROM,
      },
      template: {
        dir: __dirname + '/templates',
        adapter: new HandlebarsAdapter(),
      },
    }),
  ],
  providers: [MailerService],
  exports: [MailerService],
})
export class MailerModule {}
```

So, of course, we're also changed the .env file with the new parameters.

**Comment by pthoelken** [comment]
So, another bug from Console is this here, when I click on "Team Edit" in the right top corner @balub. I'm a lil bit confused about the bunch of errors in hoppscotch in our scenario. 

```
hoppscotch-aio    | Backend Server | [Nest] 62  - 09/13/2023, 9:15:16 AM   ERROR [ExceptionsHandler] bug/team/no_team_id
hoppscotch-aio    | Backend Server | Error: bug/team/no_team_id
hoppscotch-aio    | Backend Server |     at GqlTeamMemberGuard.canActivate (/usr/src/app/packages/hoppscotch-backend/dist/team/guards/gql-team-member.guard.js:34:19)
hoppscotch-aio    | Backend Server |     at GuardsConsumer.tryActivate (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
hoppscotch-aio    | Backend Server |     at async canActivateFn (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:158:33)
hoppscotch-aio    | Backend Server |     at async target (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:76:31)
hoppscotch-aio    | Backend Server |     at async Object.team (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
hoppscotch-aio    | Backend Server | Query Complexity: 18
hoppscotch-aio    | Backend Server | [Nest] 62  - 09/13/2023, 9:15:16 AM   ERROR [ExceptionsHandler] bug/team/no_team_id
hoppscotch-aio    | Backend Server | Error: bug/team/no_team_id
hoppscotch-aio    | Backend Server |     at GqlTeamMemberGuard.canActivate (/usr/src/app/packages/hoppscotch-backend/dist/team/guards/gql-team-member.guard.js:34:19)
hoppscotch-aio    | Backend Server |     at GuardsConsumer.tryActivate (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/guards/guards-consumer.js:15:34)
hoppscotch-aio    | Backend Server |     at async canActivateFn (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:158:33)
hoppscotch-aio    | Backend Server |     at async target (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:76:31)
hoppscotch-aio    | Backend Server |     at async Object.team (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
```

**Comment by pthoelken** [comment]
@JoelJacobStephen - the i18n errors are still there after refreshing the page.

**Comment by pthoelken** [comment]
Any new informations / updates in this case @balub @JoelJacobStephen? Currently we're in a decision process about which software we're should use and maybe you can help us to use your product.

**Comment by balub** [comment]
@pthoelken I apologise for the delay, the inability to replicate the issue is proving to be a blocker in trying to identify what the issue actually is. The `Error: user_settings/settings_already_exists` error being thrown in the backend is not of concern this is a known behaviour and is not an issue. I ask that you give us a bit more time to figure this out.

**Comment by pthoelken** [comment]
@balub - Thanks for your response. Will your fix solve the page-refresh-struggle as well?

**Comment by balub** [comment]
Yup, we are looking into solving all the issues pointed out here.

**Comment by pthoelken** [comment]
Sound perfect. Can you guess how much time will it take? Like 1 week or more? :)

**Comment by balub** [comment]
We are looking into this issue as a priority and rest assured getting it resolved is of utmost importance right now.

**Comment by balub** [comment]
@pthoelken could you share with us the graphql query that is sent to the backend server when you try to edit a team that triggered the backend to throw the `Error: bug/team/no_team_id` error earlier?

**Comment by pthoelken** [comment]
@balub - how / where can I grab this? I do this out from the UI in the right top corner (edit Team)

**Comment by balub** [comment]
Could you simply just trigger the operation and then share the graphql query being sent from the network tab.

**Comment by pthoelken** [comment]
Here is one of these

```
query Me {
      me {
        uid
        displayName
        email
        photoURL
        isAdmin
        createdOn
      }
    }
```

I don't know which do you mean exactly bc their a buch of graphql requests. 

![image](https://github.com/hoppscotch/hoppscotch/assets/12643853/bb44ee6d-3c24-473e-bfda-ea4fe9bf476e)

**Comment by pthoelken** [comment]
Other topic; is there a configuration or other way to disable this spammy log entries in my container? 

```
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 15
hoppscotch-aio    | Backend Server | Query Complexity: 18
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 15
hoppscotch-aio    | Backend Server | Query Complexity: 18
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 15
hoppscotch-aio    | Backend Server | Query Complexity: 18
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 15
hoppscotch-aio    | Backend Server | Query Complexity: 18
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 15
hoppscotch-aio    | Backend Server | Query Complexity: 18
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 22
hoppscotch-aio    | Backend Server | Query Complexity: 15
hoppscotch-aio    | Backend Server | Query Complexity: 18
hoppscotch-aio    | Backend Server | Query Complexity: 22
```

This comes up every second.

**Comment by balub** [comment]
@JoelJacobStephen what query is called when we edit the team?

**Comment by pthoelken** [comment]
@balub  with the chrome extension "GraphQL Network" i found the request: 

**GetTeam**
```
query GetTeam($teamID: ID!) {
  team(teamID: $teamID) {
    id
    name
    teamMembers {
      membershipID
      user {
        uid
        email
      }
      role
    }
  }
}
{
  "teamID": ""
}
```

**GetPendingInvites**
```
query GetPendingInvites($teamID: ID!) {
  team(teamID: $teamID) {
    id
    teamInvitations {
      inviteeRole
      inviteeEmail
      id
    }
  }
}
{
  "teamID": ""
}
```

![image](https://github.com/hoppscotch/hoppscotch/assets/12643853/b9b46733-5fd9-4cb0-b1bb-f839ecfc9bb5)

**Comment by balub** [comment]
No `teamID` is being sent, can you check the earlier queries where to see if data was fetched properly.

**Comment by pthoelken** [comment]
Yep usually the teams will be fetechd. The error comes up when I click on "Edit Teams" only. 

![image](https://github.com/hoppscotch/hoppscotch/assets/12643853/f35824e8-0715-45d2-a564-edae2a448aa9)

**Comment by balub** [comment]
@pthoelken the error you encounter when you click on "Edit Teams" usually happens when the modal first appears, however, I think the queries go through successfully after a little while if the modal is left open. We have identified this erroneous behaviour and will fix it in the meantime can you confirm the same on your end?

**Comment by pthoelken** [comment]
yep. I can confirm.

**Comment by pthoelken** [comment]
Hey @balub, any updates for me in this case? Best regards.

**Comment by balub** [comment]
Hey @pthoelken , we've identified some issues and are currently working on fixing them.

**Comment by Zer0S2m** [comment]
Hey @balub, is there any news on this open issue?

**Comment by pthoelken** [comment]
> Hey @balub, is there any news on this open issue?

He told us two days ago that the team is working on this issue :-)

**Comment by pthoelken** [comment]
As I can see, some PR are created releated to this issue. Is there a way to define a week / date which the whole issue is completed? @balub 

- gql team id bug
- missing translation in admin dashboard
- refresh trouble in the whole application

**Comment by pthoelken** [comment]
Any updates @balub ?

**Comment by pthoelken** [comment]
@balub  and team ... since multiple weeks no response? The bug is still there - check out the attached video. 

https://github.com/hoppscotch/hoppscotch/assets/12643853/604303a0-8254-45b6-ab9e-b555954e20f4

**Comment by vine-mxm** [comment]
@pthoelken did you manage to solve this? i'm facing the exact same issue. 
i'm using hoppscotch-aio self hosted on a kubernetes cluster.

**Comment by 0xdnL** [comment]
bump, I'm also experiencing this behavior self-hosted on kubernetes and having microsoft as auth_provider

**Comment by pthoelken** [comment]
> bump, I'm also experiencing this behavior self-hosted on kubernetes and having microsoft as auth_provider

Check your callback URI in the env .. in my case the URI was inserted twice. Can you paste your env without sensible data?

**Comment by pthoelken** [comment]
> @pthoelken did you manage to solve this? i'm facing the exact same issue. i'm using hoppscotch-aio self hosted on a kubernetes cluster.

Sorry for my late reply. Yes in our environment it is solved. The cause was a double URI entry in the env file.

**Comment by 0xdnL** [comment]
no worries
```
MICROSOFT_CALLBACK_URL: https://hoppscotch.foo.bar/v1/auth/microsoft/callback
```
after login I don't get to see the login page but get redirected to /v1/auth/microsoft and 404

**Comment by pthoelken** [comment]
> ```
> MICROSOFT_CALLBACK_URL: https://hoppscotch.foo.bar/v1/auth/microsoft/callback
> ```
> 
> after login I don't get to see the login page but get redirected to /v1/auth/microsoft and 404
> 
> but when I clear the site-data and refresh I'm logged in again

Sorry, I mean the REDIRECT_URL + WHITELISTED_ORIGINS from the .env 

Maybe you can provice the whole .env file without sensible data?

**Comment by 0xdnL** [comment]
partial environment variables

```
ENABLE_SUBPATH_BASED_ACCESS: "true"   # for aoi-container set to false
..
REDIRECT_URL: "https://hoppscotch.foo.bar.systems/"
WHITELISTED_ORIGINS: "https://hoppscotch.foo.bar.systems,http://hoppscotch-backend:3170,http://hoppscotch-app:3000,http://hoppscotch-backend:3100,http://localhost:3000,http://localhost:3100,http://localhost:3170"
VITE_ALLOWED_AUTH_PROVIDERS: MICROSOFT,EMAIL
MICROSOFT_CALLBACK_URL: https://hoppscotch.foo.bar.systems/v1/auth/microsoft/callback
MICROSOFT_SCOPE: "user.read"
..
VITE_APP_TOS_LINK:            https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK: https://docs.hoppscotch.io/support/privacy
VITE_BASE_URL:           https://hoppscotch.foo.bar.systems           # http://localhost:3000
VITE_SHORTCODE_BASE_URL: https://hoppscotch.foo.bar.systems           # http://localhost:3000
VITE_ADMIN_URL:          https://hoppscotch.foo.bar.systems           # http://localhost:3100
VITE_BACKEND_GQL_URL:    https://hoppscotch.foo.bar.systems/graphql   # http://localhost:3170/graphql
VITE_BACKEND_WS_URL:        ws://hoppscotch.foo.bar.systems/graphql   #   ws://localhost:3170/graphql
VITE_BACKEND_API_URL:    https://hoppscotch.foo.bar.systems/v1        # http://localhost:3170/v1
```

**Comment by pthoelken** [comment]
Out REDIRECT_URL is without the last / in the URL like this. 

`REDIRECT_URL: "https://hoppscotch.foo.bar"`

All other variables looks good.

**Comment by 0xdnL** [comment]
thanks, I've tested `REDIRECT_URL` without trailing slash, still 404 to `/v1/auth/microsoft`

clearing site data and refreshing the page leads to a successful login

**Comment by pthoelken** [comment]
So, after clearing browser and site cache the system works fine or still 404 error? 

In cases of still 404, can you check the URL in the browser **after** MS Auth (and call back brings you back to your system (404 page))? So in our cases it was at the time "https://hoppy.foo.bar/hoppy.foo.bar", which was the cause for the 404 failure.

**Comment by 0xdnL** [comment]
1. login -> directs to `https://hoppscotch.foo.bar/v1/auth/microsoft` and shows 404
2. clear site data and refresh, url still at `https://hoppscotch.foo.bar/v1/auth/microsoft`
3. pressing Login site goes to `https://hoppscotch.foo.bar` and a user is logged in

**Comment by pthoelken** [comment]
Yep, this was exactly the same behaivor here. In our case it was a typo in the REDIRECT_URI .. after reconfigure this and deleting all cache it works well. 

Did you update to the latest version of hoppscotch already?

**Comment by 0xdnL** [comment]
the image tags I'm using are:

```
hoppscotch/hoppscotch-backend:2024.3.4
hoppscotch/hoppscotch-frontend:2024.3.4
hoppscotch/hoppscotch-admin:2024.3.4
```

I've just noticed this access log:

```
"POST /graphql HTTP/2.0" 200 1696 "https://hoppscotch.foo.bar/v1/auth/microsoft?redirect_uri=https://hoppscotch.foo.bar"
```

for some reason the url in the browser doesn't show the url parameter `redirect_url`
