### ISSUE TITLE
[bug]: continuous error print in log

### ISSUE THREAD

**Issue by pankajmyt** [hoppscotch/hoppscotch#3491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am seeing following log snippet constantly being dumped by the backend docker container.

```
docker container logs a9f650acf92a --follow
```

```
[Nest] 19  - 10/30/2023, 7:30:34 AM   ERROR [ExceptionsHandler] team/member_not_found
Error: team/member_not_found
    at GqlTeamMemberGuard.canActivate (/usr/src/app/dist/team/guards/gql-team-member.guard.js:37:19)
    at async GuardsConsumer.tryActivate (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)
    at async canActivateFn (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-context-creator.js:158:33)
    at async target (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-context-creator.js:76:31)
    at async /usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
```

### Steps to reproduce

Try to follow backend docker container logs

### Environment

Production

### Version

Self-hosted

**Comment by nicklasring** [comment]
We also encountered this, might have been triggered by adding a workspace with owner (email) that does not exist

**Comment by syorito-hatsuki** [comment]
I see same issue. I have only 1 namespace and 1 user authorized using Github OAuth (else disabled)

UPD: Removed all workspace, error stay. Removed user, error stops
