### ISSUE TITLE
[bug]: can't login in any way - AIO setup over k8s

### ISSUE THREAD

**Issue by IliaGe** [hoppscotch/hoppscotch#3558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm running the hoppscotch/hoppscotch:v3.0.1 AIO version in k8s, and I have followed the install guide and created all the .env variables: (some with masked data in the post):
JWT_SECRET:                                         secret
      TOKEN_SALT_COMPLEXITY:                               10
      MAGIC_LINK_TOKEN_VALIDITY:                           3
      REFRESH_TOKEN_VALIDITY:                              604800000
      ACCESS_TOKEN_VALIDITY:                               86400000
      SESSION_SECRET:                                      another-secret
      REDIRECT_URL:                                        https://hop.infra.net
      WHITELISTED_ORIGINS:                                 https://hop.infra.net
      VITE_ALLOWED_AUTH_PROVIDERS:                         GOOGLE
      GOOGLE_CLIENT_ID:                                    257188-sss.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET:                                yyyy
      GOOGLE_CALLBACK_URL:                                 https://hop.infra.net/v1/auth/google/callback
      GOOGLE_SCOPE:                                        email,profile
      RATE_LIMIT_TTL:                                      60
      RATE_LIMIT_MAX:                                      1000
      VITE_BASE_URL:                                       https://hop.infra.net
      VITE_SHORTCODE_BASE_URL:                             https://hop.infra.net
      VITE_ADMIN_URL:                                      https://hop.infra.net
      VITE_BACKEND_GQL_URL:                                http://localhost:3170/graphql
      VITE_BACKEND_WS_URL:                                 wss://localhost:3170/graphql
      VITE_BACKEND_API_URL:                                http://localhost:3170/v1
      VITE_APP_TOS_LINK:                                   https://docs.hoppscotch.io/support/terms
      VITE_APP_PRIVACY_POLICY_LINK:                        https://docs.hoppscotch.io/support/privacy

The system loads but when I try to login with google I get in my browser:

index-58473f72.js:933 
        
        
       POST https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=d-hRxTtiqQrIcimh4i1wbsM 403 (Forbidden)
(anonymous) @ index-58473f72.js:933
await in (anonymous) (async)
XP @ index-58473f72.js:943
ba @ index-58473f72.js:914
lM @ index-58473f72.js:2883
xle @ index-58473f72.js:2892
Ble @ index-58473f72.js:5169
L4 @ auth.ts:276
signInWithEmail @ Login.vue:266
(anonymous) @ Login.vue:40
(anonymous) @ runtime-dom.esm-bundler.js:1481
Uo @ runtime-core.esm-bundler.js:155
ni @ runtime-core.esm-bundler.js:164
n @ runtime-dom.esm-bundler.js:369
Login.vue:272 FirebaseError: Firebase: Error (auth/requests-from-referer-https://hop.infra.net-are-blocked.).
    at Cw (index-58473f72.js:474:41)
    at pi (index-58473f72.js:445:11)
    at XP (index-58473f72.js:976:17)
    at async Ble (index-58473f72.js:5169:5)
    at async L4 (auth.ts:276:10)
    at async Proxy.signInWithEmail (Login.vue:266:7)

### Steps to reproduce

apply the stated config

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
We now have an official helm-chart for k8s deployments at https://github.com/hoppscotch/helm-charts.

If you still have trouble self-hosting after reading the updated documentation, please let us know. You can find it at https://docs.hoppscotch.io/documentation/self-host/helm-chart-deployment/getting-started.
