### ISSUE TITLE
[bug]: Cannot Update Authentication Providers

### ISSUE THREAD

**Issue by sats268842** [hoppscotch/hoppscotch#3679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am experiencing an issue when attempting to update the Authentication Providers(Microsoft). 

App Version: v2023.12.0-1

```
{
    "errors": [
        {
            "message": "infra_config/service_not_configured",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "enableAndDisableSSO"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "stacktrace": [
                    "Error: infra_config/service_not_configured",
                    "    at throwErr (/usr/src/app/packages/hoppscotch-backend/dist/utils.js:14:11)",
                    "    at InfraConfigService.enableAndDisableSSO (/usr/src/app/packages/hoppscotch-backend/dist/infra-config/infra-config.service.js:167:42)",
                    "    at InfraResolver.enableAndDisableSSO (/usr/src/app/packages/hoppscotch-backend/dist/admin/infra.resolver.js:131:57)",
                    "    at /usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:67:33",
                    "    at async target (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)",
                    "    at async Object.enableAndDisableSSO (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)"
                ]
            }
        }
    ],
    "data": null
}
```

### Steps to reproduce

1. Go to Admin Website
2. Click on Setting page
3. Update the authentication providers with Microsoft cred
4. try to save

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment]
@sats268842 Can I take a look at your `.env` file, there is a known issue we are working on right now related to auth providers and their callback URLs. Since you mentioned you use microsoft, may I suggest you add the following 2 variables into the `.env` file and restart the server?
* `MICROSOFT_CALLBACK_URL`
* `MICROSOFT_SCOPE`
* `MICROSOFT_TENANT`

**Comment by sats268842** [comment]
```
# Microsoft Auth Config
MICROSOFT_CALLBACK_URL=*****/v1/auth/microsoft/callback
MICROSOFT_SCOPE=user.read
MICROSOFT_TENANT=common
MICROSOFT_CLIENT_SECRET=********
MICROSOFT_CLIENT_ID=*********
```
Current Configuration .env file

**Comment by balub** [comment]
@sats268842 We will have a point release coming soon that will hopefully fix this issue.

**Comment by sats268842** [comment]
@balub I can disable the auth provider, but I can't enable it again, so I have to reset configuration from the UI.
