### ISSUE TITLE
[bug]: Selfhosted hoppscotch backend container retrun an error with mail

### ISSUE THREAD

**Issue by AhmedmmAli** [hoppscotch/hoppscotch#3714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to deploy hoppscotch self hosted on a VM, I configured the .env file and build the containers but the backend container keeps restarting and retrun this error with the email feature
`Backend Server | [Nest] 45  - 01/03/2024, 4:08:36 PM   ERROR [ExceptionHandler] Cannot create property 'mailer' on string 'XXXXXX'
Backend Server | TypeError: Cannot create property 'mailer' on string 'XXXX'
Backend Server |     at new Mail (/usr/src/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/mailer/index.js:45:33)
Backend Server |     at module.exports.createTransport (/usr/src/app/node_modules/.pnpm/nodemailer@6.9.1/node_modules/nodemailer/lib/nodemailer.js:53:14)
Backend Server |     at MailerTransportFactory.createTransport (/usr/src/app/node_modules/.pnpm/@nestjs-modules+mailer@1.9.1_@nestjs+common@10.2.7_@nestjs+core@10.2.7_nodemailer@6.9.1/node_modules/@nestjs-modules/mailer/dist/mailer-transport.factory.js:13:49)
Backend Server |     at new MailerService (/usr/src/app/node_modules/.pnpm/@nestjs-modules+mailer@1.9.1_@nestjs+common@10.2.7_@nestjs+core@10.2.7_nodemailer@6.9.1/node_modules/@nestjs-modules/mailer/dist/mailer.service.js:55:54)
Backend Server |     at Injector.instantiateClass (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/injector/injector.js:365:19)
Backend Server |     at callback (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/injector/injector.js:65:45)
Backend Server |     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/injector/injector.js:144:24)
Backend Server |     at async Injector.loadInstance (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/injector/injector.js:70:13)
Backend Server |     at async Injector.loadProvider (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/injector/injector.js:97:9)
Backend Server |     at async /usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/injector/instance-loader.js:56:13
Exiting process because Backend Server exited with code null`

### Steps to reproduce

add .env file
docker-compose up -d

### Environment

Production

### Version

Self-hosted

**Comment by AhmedmmAli** [comment]
@liyasthomas

**Comment by balub** [comment]
@AhmedmmAli Can you share your `.env` file so that it may help us identify any issues in it?

**Comment by liyasthomas** [comment]
Please let us know if you still have trouble with self-hosting after reading the updated documentation: https://docs.hoppscotch.io/documentation/self-host/getting-started
