### ISSUE TITLE
[bug]: Self Host. Can not Login with Email. Clicked Magic link but 401

### ISSUE THREAD

**Issue by lfift** [hoppscotch/hoppscotch#4184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

version: 2024.6.0
When I log in via email, the page prompts a 401 code after clicking the received MagicLink.
I'm using a self-signed SSL certificate
![image](https://github.com/user-attachments/assets/7038bbfb-61c5-4f9a-87d6-090b575d1ad5)
![image](https://github.com/user-attachments/assets/3c689584-9bde-435f-af14-d88d4a248673)

### Steps to reproduce

1.Click to Login
2.Enter Email Address
3.Click Magic link
4.The page displays 401 and the browser console displays that there is a problem with the SSL certificate. Can't I use a self-signed certificate?

### Environment

Deploy preview

### Version

Self-hosted

**Comment by lfift** [comment]
using AIO container

**Comment by nayelimdejesus** [comment]
I would like to work on this issue.

**Comment by ngoc-minh-do** [comment]
I have the same issue using AIO container

**Comment by faritor** [comment]
use AIO image

i discovered the problem through the console of the browser. I use the http protocol, When requesting the interface of `:3170/v1/auth/verify`, the returned http status code was`401`.  `post` request body parameters format is `{"token":"*****","deviceIdentifier":"*****"}`


how should I solve this problem

**Comment by mirarifhasan** [comment]
Hey @faritor —
Could you let us know if increasing the `MAGIC_LINK_TOKEN_VALIDITY` resolved the `401` error on your end?

@ngoc-minh-do —
Would you mind sharing more detailed steps or context so we can try to reproduce the issue locally?

@lfift 
Is this issue still occurring for you, or has it been resolved?

**Comment by srifqi** [comment]
> [@srifqi](https://github.com/srifqi) — Is this issue still occurring for you, or has it been resolved?

Did you mean to mention @lfift instead of me, @mirarifhasan?

**Comment by faritor** [comment]
> Hey [@faritor](https://github.com/faritor) — Could you let us know if increasing the `MAGIC_LINK_TOKEN_VALIDITY` resolved the `401` error on your end?
> 
> [@ngoc-minh-do](https://github.com/ngoc-minh-do) — Would you mind sharing more detailed steps or context so we can try to reproduce the issue locally?
> 
> [@lfift](https://github.com/lfift) Is this issue still occurring for you, or has it been resolved?

Hi, @mirarifhasan ,

thank you for your reply.  my configuration is as follows.  according to the documentation, the email should expire within 3 days.  however, from receiving the email to clicking to open it, it took no more than 3 minutes.  I'm using the chrome browser, and the version is 138.0.7204.158

```
JWT_SECRET="a9******cabf"
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY=3
REFRESH_TOKEN_VALIDITY=604800000
ACCESS_TOKEN_VALIDITY=86400000
SESSION_SECRET="5****81"
ALLOW_SECURE_COOKIES=false
```

**Comment by mirarifhasan** [comment]
@faritor 
`MAGIC_LINK_TOKEN_VALIDITY` is in hours — thanks for pointing that out. We've checked the docs and will update the clarification shortly.

We're also aware of a timezone-related issue affecting link validation, and we're aiming to address that in an upcoming release.

**Comment by faritor** [comment]
> [@faritor](https://github.com/faritor) `MAGIC_LINK_TOKEN_VALIDITY` is in hours — thanks for pointing that out. We've checked the docs and will update the clarification shortly.
> 
> We're also aware of a timezone-related issue affecting link validation, and we're aiming to address that in an upcoming release.

Hi, @mirarifhasan ,

thank you for your reply.  I'm looking forward to a fix.  currently, I'm stuck at the email login stage and can't proceed to the next step of the experience.

**Comment by faritor** [comment]
I think it's probably an issue with the expiration processing here. I set `MAGIC_LINK_TOKEN_VALIDITY` to 8640000 and I logged in successfully.


after successfully logging in, I noticed this error line in the log of the container. I'm not sure what impact it will have

```
hoppscotch  | Backend Server | [Nest] 42  - 07/23/2025, 9:20:23 PM   ERROR [ExceptionsHandler] Error: user_settings/settings_already_exists
hoppscotch  | Backend Server |     at throwErr (/dist/backend/dist/utils.js:26:11)
hoppscotch  | Backend Server |     at UserSettingsResolver.createUserSettings (/dist/backend/dist/user-settings/user-settings.resolver.js:36:34)
```

**Comment by mirarifhasan** [comment]
`user_settings/settings_already_exists` is a known behavior — no worries. The error occurs because the frontend is calling the same API twice, which leads to a duplicate "user settings already exist" response from the backend. We're aware of it and it's not something to be concerned about.

Yes, increasing the `MAGIC_LINK_TOKEN_VALIDITY` is a good workaround for now and helps ensure smoother usage. That said, we're aware of the timezone handling issue and plan to address it soon to make the experience more reliable.

**Comment by liyasthomas** [comment]
This issue has been resolved in the latest version.
