### ISSUE TITLE
[bug]: how to use mailer credential aws ses for mail provider?

### ISSUE THREAD

**Issue by jams008** [hoppscotch/hoppscotch#4192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, i have problem to use ses aws credential for email login in environment config. 
I get this error if I use a config like this.
```
MAILER_SMTP_URL=smtps://********:*****@email-smtp.us-east-1.amazonaws.com
```
Error:
```
Backend Server | Error from sendEmail: Error: getaddrinfo ENOTFOUND ***************
Backend Server |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
Backend Server |   errno: -3008,
Backend Server |   code: 'EDNS',
Backend Server |   syscall: 'getaddrinfo',
Backend Server |   hostname: '***********',
Backend Server |   command: 'CONN'
Backend Server | }
Backend Server | [Nest] 70  - 07/16/2024, 10:59:45 AM   ERROR [ExceptionsHandler] email/failed
Backend Server | Error: email/failed
Backend Server |     at throwErr (/usr/src/app/packages/hoppscotch-backend/dist/utils.js:15:11)
Backend Server |     at MailerService.sendEmail (/usr/src/app/packages/hoppscotch-backend/dist/mailer/mailer.service.js:47:41)
Backend Server |     at async AuthService.signInMagicLink (/usr/src/app/packages/hoppscotch-backend/dist/auth/auth.service.js:159:9)
Backend Server |     at async AuthController.signInMagicLink (/usr/src/app/packages/hoppscotch-backend/dist/auth/auth.controller.js:48:
```
I also tried using a custom email config. I did not experience the 500 status code error and the error was not in the log. but the login email was not sent.

thanks

### Steps to reproduce

1. Set config env to provider login via email
2. add MAILER_SMTP_URL using aws ses credential
3. test login via email

### Environment

Production

### Version

Self-hosted

**Comment by aryaag** [comment]
@jams008 I have shared my config [in this comment](https://github.com/hoppscotch/hoppscotch/issues/3257#issuecomment-2348832805) with common errors. Maybe it will help you.

**Comment by jams008** [comment]
Thanks for the repley

**Comment by liyasthomas** [comment]
There have been a lot of changes to the platform. If you're still having problems with the latest version, please let us know.
