### ISSUE TITLE
[bug]: [Nest] 36  - 11/24/2024, 5:29:51 AM   ERROR [ExceptionsHandler] "expiresIn" should be a number of seconds or string representing a timespan eg: "1d", "20h", 60

### ISSUE THREAD

**Issue by iam-abdul** [hoppscotch/hoppscotch#4553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to self host the hoppscotch and i think there is some issue with the way we have to pass the environment variables in the .env file.

Because of following environment variables the sign in via github is failing. I tried passing 7d, 604800 and "7d", nothing seems to work. 

REFRESH_TOKEN_VALIDITY="7d"
ACCESS_TOKEN_VALIDITY="1d"

```

Backend Server | Query Complexity: 3
Backend Server | Query Complexity: 4
Backend Server | Query Complexity: 7
Backend Server | Query Complexity: 3
Backend Server | Query Complexity: 17
Backend Server | Query Complexity: 2
Backend Server | [Nest] 37  - 11/24/2024, 5:50:22 AM   ERROR [ExceptionsHandler] "expiresIn" should be a number of seconds or string representing a timespan eg: "1d", "20h", 60
Backend Server | Error: "expiresIn" should be a number of seconds or string representing a timespan eg: "1d", "20h", 60
Backend Server |     at module.exports [as sign] (/dist/backend/node_modules/.pnpm/jsonwebtoken@9.0.2/node_modules/jsonwebtoken/sign.js:213:22)
Backend Server |     at JwtService.sign (/dist/backend/node_modules/.pnpm/@nestjs+jwt@10.2.0_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14.1_refle_p73cogk5aumciauu2q42yaxpfq/node_modules/@nestjs/jwt/dist/jwt.service.js:41:20)
Backend Server |     at AuthService.generateRefreshToken (/dist/backend/dist/auth/auth.service.js:76:52)
Backend Server |     at AuthService.generateAuthTokens (/dist/backend/dist/auth/auth.service.js:94:41)
Backend Server |     at AuthController.githubAuthRedirect (/dist/backend/dist/auth/auth.controller.js:74:51)
Backend Server |     at /dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14.1_refl_uclmhdhodpinoxc7fwisrergn4/node_modules/@nestjs/core/router/router-execution-context.js:38:29
```

### Steps to reproduce

use these env variables

REFRESH_TOKEN_VALIDITY="604800000"
ACCESS_TOKEN_VALIDITY="86400000"

### Environment

Production

### Version

Self-hosted

**Comment by mirarifhasan** [comment]
Hi @iam-abdul 
Hope the discussion of issue #4205 will solve your error.

**Comment by iam-abdul** [comment]
thanks @mirarifhasan this helped
