### ISSUE TITLE
[bug]: Empty MAILER_SMTP_USER and MAILER_SMTP_PASSWORD considered invalid

### ISSUE THREAD

**Issue by FrankyBoy** [hoppscotch/hoppscotch#4586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

From `.env` file:

```
# Mailer config
MAILER_SMTP_ENABLE=true
MAILER_USE_CUSTOM_CONFIGS=true
MAILER_ADDRESS_FROM=hoppscotch@foo.bar
MAILER_SMTP_HOST=smtp.foo.bar
MAILER_SMTP_PORT=25
MAILER_SMTP_SECURE=false
MAILER_SMTP_USER=
MAILER_SMTP_PASSWORD=
MAILER_TLS_REJECT_UNAUTHORIZED=false
```

Hoppscotch consideres this config to be invalid and does not start:

```
hoppscotch-1   | Backend Server | Error: auth/provider_not_configured_correctly
hoppscotch-1   | Backend Server |     at throwErr (/dist/backend/dist/utils.js:26:11)
hoppscotch-1   | Backend Server |     at getConfiguredSSOProvidersFromEnvFile (/dist/backend/dist/infra-config/helper.js:329:30)
hoppscotch-1   | Backend Server |     at getDefaultInfraConfigs (/dist/backend/dist/infra-config/helper.js:81:36)
hoppscotch-1   | Backend Server |     at InfraConfigService.initializeInfraConfigTable (/dist/backend/dist/infra-config/infra-config.service.js:55:83)
hoppscotch-1   | Backend Server |     at InfraConfigService.onModuleInit (/dist/backend/dist/infra-config/infra-config.service.js:51:20)
hoppscotch-1   | Backend Server |     at MapIterator.iteratee (/dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14.1_refl_uclmhdhodpinoxc7fwisrergn4/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
hoppscotch-1   | Backend Server |     at MapIterator.next (/dist/backend/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/map.js:13:39)
hoppscotch-1   | Backend Server |     at IteratorWithOperators.next (/dist/backend/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/iterate.js:21:28)
hoppscotch-1   | Backend Server |     at Function.from (<anonymous>)
hoppscotch-1   | Backend Server |     at IteratorWithOperators.toArray (/dist/backend/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/iterate.js:180:22)
hoppscotch-1   | Backend Server | /dist/backend/dist/utils.js:26
hoppscotch-1   | Backend Server |     throw new Error(errMessage);
hoppscotch-1   | Backend Server |           ^
hoppscotch-1   | Backend Server |
hoppscotch-1   | Backend Server | Error: Error: auth/provider_not_configured_correctly
hoppscotch-1   | Backend Server |     at throwErr (/dist/backend/dist/utils.js:26:11)
hoppscotch-1   | Backend Server |     at InfraConfigService.initializeInfraConfigTable (/dist/backend/dist/infra-config/infra-config.service.js:95:38)
hoppscotch-1   | Backend Server |     at async InfraConfigService.onModuleInit (/dist/backend/dist/infra-config/infra-config.service.js:51:9)
hoppscotch-1   | Backend Server |
hoppscotch-1   | Backend Server | Node.js v20.18.1
hoppscotch-1   | Exiting process because Backend Server exited with code 1
```

This is incorrect behaviour as anonymous SMTP is not an invalid configuration but something that exists especially in internal networks. 

### Steps to reproduce

1. Create config with above settings
2. start hoppscotch
3. observe failure

### Environment

Production

### Version

Self-hosted

**Comment by mirarifhasan** [comment]
Hi @FrankyBoy 
If you'd prefer to keep the SMTP configuration without needing a `user` and `password`, you can set your `.env` file as following. This way, you won't need to provide a `user` and `password`.

```
MAILER_USE_CUSTOM_CONFIGS=false
MAILER_SMTP_URL=smtp://host:port
```

**Comment by FrankyBoy** [comment]
@mirarifhasan that is not an option, as that version always wants to go with STARTTLS, which is not an option for other reasons. Also "just don't use the buggy path" is not a valid fix, sorry.

**Comment by MadWalnut** [comment]
@FrankyBoy Did you find a workaround for this? I also want to use unencrypted SMTP on port 25 without login.

**Comment by jamesgeorge007** [comment]
Closing since this is addressed in the [v2026.3.0 release](https://github.com/hoppscotch/hoppscotch/releases/tag/2026.3.0).
